import schedule_tasks
import site_inspection
import survey_details
import view_plan_tasks
import users
import customer_details
import atm_details
import cust_alerts
import internal_alerts
import public_holidays
import state_setup
import reason_code_setup
import remark_category
import customer_details
import atm_details
